### ISSUE TITLE
Feature request: Can we recognize multiple faces at once ?

### ISSUE THREAD

**Issue by vivekshah-zymr** [NovaTecConsulting/FaceRecognition-in-ARKit#5]
Hello,
I am working on the demo where I have a similar requirement. But I have to recognize multiple person's faces at once. So here can we recognize multiple faces at once?
Thanks in advance.

**Comment by jagatfx** [comment]
@vivekshah-zymr The `VNDetectFaceRectanglesRequest` used in the demo code returns an array of face rectangles for each face. It already recognizes multiple faces at once.

**Comment by m-ruhl** [comment]
As @jagatfx already said. It's possible.
