### ISSUE TITLE
From where do you show the image icon of the recognized person ?

### ISSUE THREAD

**Issue by umarF** [NovaTecConsulting/FaceRecognition-in-ARKit#7]
Hi,

I went through the code but I couldnt make out how are you able to show the image icon of the person who's recognized like Boris with his image.

Where are those image being pulled from ?
and which part of code handles it.

Thanks.

**Comment by m-ruhl** [comment]
Hi @umarF,

The images were included as resources in the app, but I didn't upload those here.

It just looks for an image as the person's name:
https://github.com/NovaTecConsulting/FaceRecognition-in-ARKit/blob/6f8d886a861a162475402c5f4dfa200c376e6b28/faceIT/SCNNode%2BText.swift#L41

**Comment by umarF** [comment]
Thanks.
