### ISSUE TITLE
This model only recognize faces trained?

### ISSUE THREAD

**Issue by clockwiser** [NovaTecConsulting/FaceRecognition-in-ARKit#9]
The training data is classified for each person.
1. Each person has over 300 augmented photos.
2. Each person is classified as one class.
3. Plus other photos not classified as a person above, rather classified just as other class.

In the example, there are 4 classes, 3 for each person, 1 for others.

Train with these photos would recognize only classified persons.
That is one of  the reasons why model is not provided, because this model recognizes
only the three people.

**Comment by m-ruhl** [comment]
Yes, you need to train the faced you later want to classify
